#pragma once

#include <windows.h>

extern HBRUSH BACKGROUND_BRUSH;
extern HBRUSH LABEL_BACKGROUND_BRUSH;
extern HBRUSH BUTTON_BACKGROUND_BRUSH;
extern HBRUSH BUTTON_PRESSED_BRUSH;
extern HBRUSH BUTTON_HOT_BRUSH;
extern HBRUSH BUTTON_WHITE_BRUSH;
extern COLORREF LABEL_TEXT_COLOR;
extern COLORREF BUTTON_TEXT_COLOR;

extern bool OWNER_DRAW;
